name: test ci pipeline
run-name: ${{ github.actor }} is testing the ci!
on: [push]
jobs:
  learning:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world!"
      - name: "checkout"
        uses: actions/checkout@v4
      - run: echo "job status is ${{ job.status }}"
  testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - run: echo "hello world!"
      - name: initng node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run : npm install -g pnpm
      - run : pnpm install
      - run : pnpn test:e2e
      - run : "job status is ${{ job.status }}"
        