name: test ci pipeline
run-name: ${{ github.actor }} is testing the ci!
on: [push]
jobs:
  learning:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world!"
      - run: echo "this job triggered by ${{ github.event_name }}"
      - run: echo "branch ${{ github.ref }}"
      - run: echo "user ${{ github.actor }} triggered the job!"
      - name: checking out
        uses: actions/checkout@v4
      - run: echo "testing"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "job status is ${{ job.status }}"