name: test ci pipeline
run-name: ${{ github.actor }} is testing the ci!
on: [push]
jobs:
  learning:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world!"
      - name: "checkout"
        uses: actions/checkout@v4
      - run: echo "job status is ${{ job.status }}"
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g pnpm
      - run: pnpm install
        working-directory: ./api-gateway-auth
      - run: pnpm test
        working-directory: ./api-gateway-auth
      - run: echo "job status is ${{ job.status }}"
        